// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/notes/data/models/note_chunk_objectbox.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5635374471380766312),
    name: 'NoteChunkObjectBox',
    lastPropertyId: const obx_int.IdUid(6, 902412261957039145),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4903973965032274697),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4802865032664745559),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4965542788751364189),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 8598813251366998943),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1202960122723786264),
        name: 'sourceTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3649071792153279844),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 902412261957039145),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5635374471380766312),
    lastIndexId: const obx_int.IdUid(1, 8598813251366998943),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NoteChunkObjectBox: obx_int.EntityDefinition<NoteChunkObjectBox>(
      model: _entities[0],
      toOneRelations: (NoteChunkObjectBox object) => [],
      toManyRelations: (NoteChunkObjectBox object) => {},
      getId: (NoteChunkObjectBox object) => object.id,
      setId: (NoteChunkObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (NoteChunkObjectBox object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final sourceTitleOffset = object.sourceTitle == null
            ? null
            : fbb.writeString(object.sourceTitle!);
        final createdAtOffset = object.createdAt == null
            ? null
            : fbb.writeString(object.createdAt!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.addOffset(3, sourceTitleOffset);
        fbb.addInt64(4, object.chunkIndex);
        fbb.addOffset(5, createdAtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final sourceTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final chunkIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = NoteChunkObjectBox(
          id: idParam,
          text: textParam,
          embedding: embeddingParam,
          sourceTitle: sourceTitleParam,
          chunkIndex: chunkIndexParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NoteChunkObjectBox] entity fields to define ObjectBox queries.
class NoteChunkObjectBox_ {
  /// See [NoteChunkObjectBox.id].
  static final id = obx.QueryIntegerProperty<NoteChunkObjectBox>(
    _entities[0].properties[0],
  );

  /// See [NoteChunkObjectBox.text].
  static final text = obx.QueryStringProperty<NoteChunkObjectBox>(
    _entities[0].properties[1],
  );

  /// See [NoteChunkObjectBox.embedding].
  static final embedding = obx.QueryHnswProperty<NoteChunkObjectBox>(
    _entities[0].properties[2],
  );

  /// See [NoteChunkObjectBox.sourceTitle].
  static final sourceTitle = obx.QueryStringProperty<NoteChunkObjectBox>(
    _entities[0].properties[3],
  );

  /// See [NoteChunkObjectBox.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<NoteChunkObjectBox>(
    _entities[0].properties[4],
  );

  /// See [NoteChunkObjectBox.createdAt].
  static final createdAt = obx.QueryStringProperty<NoteChunkObjectBox>(
    _entities[0].properties[5],
  );
}
